function figure1=DataFig(xmin, xmax,ymin, ymax,stim)

%CREATEFIGURE
 
%  Auto-generated by MATLAB on 07-May-2007 23:35:04
 
% Create figure

figure1 = figure('Color',[1 1 1],'Position',[1 1 700 600]);
 
boxcolor=[0.9 0.9 0.9];


% % COLORS:
% % CO2_0.5%  [0.7529  0.7529  0.7529] %Silver gray
% % CO2_1.0%  [0.5294  0.8078  0.9804] %LightSkyBlue
% % CO2_5.0%  [0.4980  1.0000  0     ] %green
% % O2_12.5 [1        1       0]      %yellow
% % O2_15.0 [1.0000   0.6471  0]      %orange
% % O2_17.5 [0.9804   0.5020  0.4471] %salmon
% % O2_21.0 [0.9333   0.5098  0.9333] %violet 

% Create axes
axes1 = axes('FontSize',18,'Parent',figure1);
axis([xmin xmax ymin ymax]);


for i=1:2:length(stim)-1

bx(i)=rectangle('Position',[stim(i),0,stim(i+1),ymax],'FaceColor',boxcolor,'LineStyle','none');

end


% bx1=rectangle('Position',[0,0,360,yaxsc],'FaceColor',boxcolor,'LineStyle','none');
% bx2=rectangle('Position',[720,0,360,yaxsc],'FaceColor',boxcolor,'LineStyle','none');


% bx1=rectangle('Position',[60,0,1,yaxsc],'FaceColor',boxcolor,'LineStyle','none');
% bx2=rectangle('Position',[121,0,10,yaxsc],'FaceColor',boxcolor,'LineStyle','none');
% bx3=rectangle('Position',[191,0,100,yaxsc],'FaceColor',boxcolor,'LineStyle','none');





set(axes1,'layer','top');

box('on');
hold('all');
grid('on');
 

 
